repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
  # -   repo: https://github.com/psf/black
  #     rev: 22.3.0
  #     hooks:
  #     - id: black
  #       language_version: python3
  - repo: https://github.com/omnilib/ufmt
    rev: v2.0.1
    hooks:
      - id: ufmt
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: [--ignore, E203]
